{{ if and (index .Values "modules" "text2vec-openai" "enabled") (index .Values "modules" "text2vec-openai" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-openai
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-openai" "apiKey" | b64enc }}
{{ end }}
